### ISSUE TITLE
Some keywords are not highlighted

### ISSUE THREAD

**Issue by yshui** [arakashic/chromatica.nvim#16]
Like 'struct', 'enum', 'if', 'return', etc. When feature_level = 1

**Comment by arakashic** [comment]
Does this commit fix your problem?

https://github.com/arakashic/chromatica.nvim/commit/293e6f46ad61d9bdd000b3645fa8bab425fa266a

**Comment by yshui** [comment]
Not quite.

It seems chromatica's highlight doesn't work for the entire file I tested. Part of the file is highlighted just fine (including keywords, etc.), and other parts are just left with no highlights.

**Comment by arakashic** [comment]
Hmm. It sounds like some flags are missing. What does `:ChromaticaShowInfo` print?

**Comment by yshui** [comment]
@arakashic I'm using compilation database generated by cmake.

**Comment by arakashic** [comment]
Might be the processing of CDB is bad. I have merged your pull request about the CDB. Still not working?

**Comment by yshui** [comment]
If I run `:ChromaticaShowInfo` I can see all the flags are there.
