### ISSUE TITLE
Remote plugin for JS highlighting

### ISSUE THREAD

**Issue by billyvg** [arakashic/chromatica.nvim#17]
I don't really know Vimscript so I used chromatica as inspiration. I've managed to create a remote plugin (node) that uses an AST to highlight js source code.

My question is would you want to see this bundled with chromatica, or would you rather it be a separate plugin?

**Comment by arakashic** [comment]
Hi @billyvg, a semantic-based highlighting for JS is very interesting! I think maintaining a JS highlight engine separately would be ideal. 

My long term plan for chromatica is to separate the chromatica core (host) and language-specific highlighting engines. This plan needs more investigation and thinking to make it work. Unfortunately, I haven't got much time to work on that recently.
