### ISSUE TITLE
chromatica throws error when -include-pch is used

### ISSUE THREAD

**Issue by haifengkao** [arakashic/chromatica.nvim#20]
If I add the precompile header flag to `.clang`, chromatica will show the following error:
![2016-08-26 3 12 13](https://cloud.githubusercontent.com/assets/4080524/17982566/f05a09f0-6b3a-11e6-8e6b-cecdc363238b.jpg)

If I remove the following flag:
`-include-pch ./Example/Tests/Tests-Prefix.pch`

everything will be fine.

`Tests-Prefix.pch` is empty, so it is not related to its content.

The libclang is the one coming from `brew install llvm`

Output of chromatic log:
```
2016-08-26 02:04:45,145 INFO     (chromatica.logging) --- Chromatica Log Start ---
2016-08-26 02:04:45,145 INFO     (chromatica.logging) NVIM v0.1.5-684-gbfa8378, Python 3.5.1, neovim client 0.1.9
```

**Comment by arakashic** [comment]
Chromatica internally uses clang with pre-compiled header to speed up reparsing. Passing `-include-pch` is conflicting with it.

**Comment by haifengkao** [comment]
Thanks.
I changed `-include-pch` to `-include` and it works!
