### ISSUE TITLE
Chromatica crashes with compile_commands.json file generated by Bear.

### ISSUE THREAD

**Issue by melonaerial** [arakashic/chromatica.nvim#21]
I've got very simple Makefile and little test program. When I've generated compile_commands.json file chromatica have crashed with the following Traceback:

>error caught in async handler 'chromatica_highlight [{'highlight_tick': 1, 'filetype': 'cpp', 'args': ['g++', 'program.o', 'main.cpp'], 'pos
ition': [1, 1], 'filename': '/home/melon/Temp/Test_project/main.cpp', 'rpc': 'chromatica_highlight', 'bufnr': 1, 'changedtick': 3, 'buffer':
 <neovim.api.buffer.Buffer object at 0x7f041353a1d0>, 'range': [1, 40]}]'
Traceback (most recent call last):
  File "/home/melon/.config/nvim/bundle/chromatica.nvim/rplugin/python3/chromatica/__init__.py", line 33, in highlight
    self.__chromatica.highlight(context)
  File "/home/melon/.config/nvim/bundle/chromatica.nvim/rplugin/python3/chromatica/chromatica.py", line 197, in highlight
    if filename not in self.ctx: return self.parse(context)
  File "/home/melon/.config/nvim/bundle/chromatica.nvim/rplugin/python3/chromatica/chromatica.py", line 99, in parse
    options=self.parse_options)
  File "/home/melon/.config/nvim/bundle/chromatica.nvim/rplugin/python3/clang/cindex.py", line 2533, in parse
    self)
  File "/home/melon/.config/nvim/bundle/chromatica.nvim/rplugin/python3/clang/cindex.py", line 2665, in from_source
    raise TranslationUnitLoadError("Error parsing translation unit.")
clang.cindex.TranslationUnitLoadError: Error parsing translation unit.

Here is my simple test project.
[chromatica-test.tar.gz](https://github.com/arakashic/chromatica.nvim/files/546625/chromatica-test.tar.gz)

So maybe I'm doing something wrong or maybe it is a bug.

**Comment by arakashic** [comment]
I tried your test project. However, I could not reproduce the issue. Can you check if your Chromatica is up to date?

Thanks for providing the test project. I does help me found another bug. :-)

**Comment by melonaerial** [comment]
@arakashic I've installed chromatica yesterday, but I've update it right now. So I still get the same error. I'm using Arch Linux with Neovim 0.1.5 , Python 3.5.2 and clang 3.8.1 . 

Here is config for chromatica from init.vim : 
let g:chromatica#libclang_path = '/usr/lib'
let g:chromatica#responsive_mode = 1
let g:chromatica#enable_at_startup = 1

Your README says that I need to put to libclang_path where is my libclang.so, so it is in "/usr/lib" . Maybe I need to put another path ? But when I put to compile_commands.json just `[]` I get rather good highlighting(not very good, but it's look that you have got the same issue as color_coded here: https://github.com/jeaye/color_coded/issues/140 , because your highlighting looks exactly the same). Anyway, with compile_commands.json generated by Bear it is crashes.

**Comment by melonaerial** [comment]
@arakashic Yeah, man. I've got it. Did read my comment https://github.com/arakashic/chromatica.nvim/issues/21#issuecomment-255623475 ? I've already updated chromatica and issue is still there. Problem is in this line of code https://github.com/arakashic/chromatica.nvim/blob/master/rplugin/python3/chromatica/chromatica.py#L197 . Parse function throws an exception. I don't know why it is happens, I will try to debug your code at the weekend and maybe I will found the bug that occurs on my installation.

**Comment by melonaerial** [comment]
@arakashic You're right. Version of project that I've given to you before is working correctly. The issue was with second version of project. Sorry for that. So this is this version of project with which you reproduce the issue.
[chromatica-2.tar.gz](https://github.com/arakashic/chromatica.nvim/files/557408/chromatica-2.tar.gz)

**Comment by melonaerial** [comment]
@arakashic So, I've found steps you need to reproduce the issue. The version of project doesn't matter. It happens on both of them. You need to set the right path in compile_commands.json file. If path is not going to real file, then everything works fine. But if path goes to main.cpp file, then Chromatica crashes.

**Comment by arakashic** [comment]
Thanks. I can reproduce the problem now. I think I know where the problem is. Should be able to fix it soon.

**Comment by arakashic** [comment]
I just pushed a patch to `master`. It should solve your problem. Basically, the bug was because the  cdb parser was expecting a "normalized" args. That is using `-o program.o -c main2.cpp` or `-c main2.cpp -o program.o` instead of `-c -o program.o main2.cpp`. I have patched it to double check and remove the source file name, which should fix the problem.

**Comment by melonaerial** [comment]
I've got it. So I've updated chromatica and now its working. Thank you very much for your work. But I've found another issue, I will close this and create another)
