### ISSUE TITLE
Class fields hightlighting if field contains :: or <> in its type.

### ISSUE THREAD

**Issue by melonaerial** [arakashic/chromatica.nvim#25]
So I've got exactly the same issue with color_coded plugin. You can see the first comment here https://github.com/jeaye/color_coded/issues/140 it describes enough about it.

This problem occurs because libclang.so uses incorrect default header search paths. So the solution of this issue for chromatica is nearly the same as for color_coded with differences of used files for compilation flags. So all you have to do is to call `echo | clang -v -E -x c++ -` and include all paths under the `#include <...> search starts here:` to your compile_command.json file. So I have included them to "command" field. So after that your "command" field will look like so: 
>"command": "c++ -c -o program.o **-I/usr/local/include -I/usr/bin/../lib/clang/3.8.1/include -I/usr/include -I/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../include/c++/6.2.1/backward -I/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../include/c++/6.2.1/x86_64-pc-linux-gnu -I/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../include/c++/6.2.1** main.cpp"

All flags started with **-I** included by me and after I've included them everything have started working fine. So this problem is also know in YCM plugin too https://github.com/Valloric/YouCompleteMe#completion-doesnt-work-with-the-c-standard-library-headers . So I think you can include some documentation about this issue to your FAQ, maybe it will help some guys.

**Comment by arakashic** [comment]
Yeah. I do remember seeing this problem back in the time when I was using YCM and color_coded. However, I just tried your latest test code and the problem is not there. I am suspecting that some of the options I used when installing llvm through homebrew and I have replaced the default clang with the homebrew version. I am going to try the bottled version and other options to see if I can reproduce the problem, hopefully soon.

**Comment by arakashic** [comment]
Well. It turns out the libclang should work fine if you installed LLVM with libcxx. And I could not find an elegant way to detect it on-the-fly.

For you situation, you can actually add those flags to `g:chromatica#global_args`, so that you don't need to add them to every CDB.
