### ISSUE TITLE
conflict with rainbow_parentheses.vim

### ISSUE THREAD

**Issue by zanglg** [arakashic/chromatica.nvim#26]
if enable chromatica.nvim, I can not see my rainbow color for parentheses

**Comment by arakashic** [comment]
Which rainbow_parenthesis are you using? https://github.com/kien/rainbow_parentheses.vim or https://github.com/junegunn/rainbow_parentheses.vim

**Comment by zanglg** [comment]
first one, thx


-------- 原始邮件 --------
主题：Re: [arakashic/chromatica.nvim] conflict with rainbow_parentheses.vim (#26)
发件人：Yanfei Guo
收件人："arakashic/chromatica.nvim"
抄送：Leigang ,Author



Which rainbow_parenthesis are you using? https://github.com/kien/rainbow_parentheses.vim or https://github.com/junegunn/rainbow_parentheses.vim

**Comment by arakashic** [comment]
OK. I can try it.

**Comment by arakashic** [comment]
Did a quick try. It seems kien/rainbow_parenthesis is broken by itself on nvim 0.1.6. No highlight for parenthesis even without chromatica.

What is your nvim version? Does kein/rainbow_parenthesis works without chromatica on your side?

FYI. I would suggest switching to junegunn/rainbow_parenthesis. kien/rainbow_parenthesis has been deserted for a long time.

**Comment by zanglg** [comment]
Thanx for first.
Disable chromatica, rainbow_parenthesis works very well~
My nvim version is NVIM 0.1.6-dev.
If junegunn/rainbow_parenthesis can exist with chromatica, I'm glad update my vundle list.

**Comment by arakashic** [comment]
kien/rainbow_parenthesis is also working fine now.
