### ISSUE TITLE
Set the path to the compilation database via a variable

### ISSUE THREAD

**Issue by snowzurfer** [arakashic/chromatica.nvim#28]
It would be very useful to set the path to the compilation database via a variable in init.vim.

I output the compilation database in the build folder of my project because I don't want it to pollute the main source tree where I only keep the source files; after all the compilation database is an artifact of building but it doesn't need to be tracked and be in the root folder of the project.
Hence it would make sense to instruct chromatica where to find it, rather than it just looking in the root folder and up the directory structure.

**Comment by arakashic** [comment]
Good suggestion. I can added this.
