### ISSUE TITLE
Improve .clang files

### ISSUE THREAD

**Issue by arakashic** [arakashic/chromatica.nvim#3]
1. Allowing multiple `flags` options

**Comment by HiPhish** [comment]
The deoplete-clang plugin allows specifying the location of the `compile_commands.json` file like this:
```
compilation_database = "<path to compilation_database>"
```
It's an alternative to specifying the flags in the file. This is useful if the compilation database is not in the root of the project. Neovim itself places the database in the `build` directory, so this allows me to just put the patch in my `.clang` file and have it always be up to date. Can Chromatica do the same?

**Comment by arakashic** [comment]
Yes. Chromatica already has the support for deoplete-clang-like configuration. I am thinking to extend it. Specifically, I am thinking to allow multiple `flags` because I don't like the state that tens of flags are all written in one line.

**Comment by HiPhish** [comment]
OK, thanks. I wasn't sure because it didn't mention that option in the documentation. Yes, I agree that putting all flags on the same like is awful.

**Comment by arakashic** [comment]
Ah. I forgot to push it is the doc. CDB support was broken, so I didn't mention it. :)
