### ISSUE TITLE
There's no `--with-clang` option for installing LLVM

### ISSUE THREAD

**Issue by darthdeus** [arakashic/chromatica.nvim#54]
This is probably something that has changed since the library was released, but

```
brew install llvm --HEAD --with-clang
```

returns the following error

```
Warning: llvm: this formula has no --with-clang option so it will be ignored!
```

Is there any other way the dependencies should be setup instead?

**Comment by arakashic** [comment]
It is by default enabled by the llvm formula now. I have updated the doc.
