### ISSUE TITLE
Does not start on Windows

### ISSUE THREAD

**Issue by aldn** [arakashic/chromatica.nvim#67]
Hello, 

https://github.com/arakashic/chromatica.nvim/commit/8538ce8a25fc58f23733975a273590e42e5d9bd6#diff-334c83188ae0960008e4609941bf11c7

With this commit Chromatica can't start on Windows anymore if you enable logging via vimrc:
```
let g:chromatica#enable_log=1
```

Without this option Chromatica can start but still fails in `:ChromaticaEnableLog` 

Quick search shows that `util.get_clang_include_path()` is used just to print log message in `Chromatica.dumg_debug_info()`.  Deleting this piece fixes the issue.

**Comment by arakashic** [comment]
Yes, that would not work on Windows generally. Are you using neovim with Windows Linux Subsystem or with something else?

**Comment by aldn** [comment]
I am using a native Windows version of Neovim with Qt frontend. https://github.com/equalsraf/neovim-qt/releases
