### ISSUE TITLE
when change the .clang profile  format?

### ISSUE THREAD

**Issue by yinflying** [arakashic/chromatica.nvim#74]
After update, I found `.clang` file like this:
```
flags=-I/home/abc/src
```
do not work, so after looooooong time trying, I found that standard `.clang` file need to change to 
```
-I/home/abc/src
```

=> which cause me a bad mood. maybe we should update the `readme.md` after changing?

**Comment by arakashic** [comment]
Sorry the frustration. It was change a while ago and the README was updated accordingly.
